INSERT INTO ROUPA (CONTATO_FORNECEDOR, COR, DESCRICAO, PRECOAVISTA, PRECO_PARCELADO, REFERENCIA, TAMANHO, UNIDADES) 
VALUES ('Fornecedor A', 'Vermelho', 'Produto 1', 100.00, 110.00, 'REF123', 'M', 10);

INSERT INTO ROUPA (CONTATO_FORNECEDOR, COR, DESCRICAO, PRECOAVISTA, PRECO_PARCELADO, REFERENCIA, TAMANHO, UNIDADES) 
VALUES ('Fornecedor B', 'Azul', 'Produto 2', 150.00, 165.00, 'REF124', 'L', 20);

INSERT INTO ROUPA (CONTATO_FORNECEDOR, COR, DESCRICAO, PRECOAVISTA, PRECO_PARCELADO, REFERENCIA, TAMANHO, UNIDADES) 
VALUES ('Fornecedor C', 'Verde', 'Produto 3', 200.00, 220.00, 'REF125', 'S', 30);
